"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!*ol=)7e(*vr$stcs$4vbzg7+k++=wjo%31ar!)q&^d0h7+yd6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False # Must be False in production

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

AUTH_USER_MODEL = 'relationship_app.CustomUser'
AUTH_USER_MODEL = 'bookshelf.CustomUser'
# LibraryProject/settings.py
LOGIN_REDIRECT_URL = '/relationship/books/'
# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'Custom',      # **REQUIRED: Replace with your actual DB name**Book_Store
        'USER': 'root',           # e.g., 'root'
        'PASSWORD': 'Root1234',       # **REQUIRED: Replace with your actual password**
        'HOST': '127.0.0.1',
        'PORT': '3306',
        # Optional: for specific configuration
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# 2. Cookie Security (Requires HTTPS)
# Ensures session cookies are only sent over HTTPS connections
SESSION_COOKIE_SECURE = True 
# Ensures CSRF cookies are only sent over HTTPS connections
CSRF_COOKIE_SECURE = True 

# 3. Browser-Side Protections
# Prevents embedding of the site in a frame/iframe (protection against clickjacking)
X_FRAME_OPTIONS = 'DENY' 
# Tells the browser not to execute scripts injected by an XSS attack
SECURE_BROWSER_XSS_FILTER = True 
# Prevents the browser from MIME-sniffing content type (mitigates XSS)
SECURE_CONTENT_TYPE_NOSNIFF = True

# 4. HTTPS/HSTS (Highly Recommended)
# Forces redirects to HTTPS (requires a web server setting too)
SECURE_SSL_REDIRECT = True 
# Sets HTTP Strict Transport Security (HSTS) max age (e.g., one year)
SECURE_HSTS_SECONDS = 31536000 
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True

# 5. Content Security Policy (For Step 4)
# Note: You need to install django-csp first: pip install django-csp
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "https://stackpath.bootstrapcdn.com",)
CSP_STYLE_SRC = ("'self'", "https://stackpath.bootstrapcdn.com",)
CSP_IMG_SRC = ("'self'", "data:",)
